/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yrvfphlbikhiaysqjanh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlydmZwaGxiaWtoaWF5c3FqYW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDU3MDUsImV4cCI6MjA3NzMyMTcwNX0.U6-5Ayfg-mUA7OgOR7RVyqTXH-QfJua7ikUde1axzZQ"