// ============================================
// NETADMIN - DATOS DE EJEMPLO
// Versión 8: Hojas de vida de ejemplo para demostración
// ============================================

export const mockEquipmentData = [
  {
    id: "1",
    id_hoja: "HV-SW-001",
    hostname: "HV-SW-S7-G8-A1",
    activo: "switch",
    fecha_registro: "2024-10-15",
    ultima_actualizacion: "2024-10-30",
    usuario_creador: "Admin Red",
    version: "1.0",
    razon_social: "grupo cos",
    site: "site7",
    gabinete: "Rack 3 - U12",
    elemento: "switch",
    marca: "Cisco",
    modelo: "Catalyst 3850-48P",
    serial: "FCW2145G0QZ",
    proveedor: "Cisco Colombia",
    fecha_compra: "2024-05-20",
    ubicacion_fisica: "Datacenter Principal - Piso 2",
    configuracion: "Switch de acceso capa 2/3 con PoE+ para telefonía IP",
    ip_direccion: "192.168.7.10",
    gateway: "192.168.7.1",
    wins_dns: "8.8.8.8, 8.8.4.4",
    funciones: "Switch de acceso para piso 2, provisión de PoE para teléfonos IP, enlaces trunk a core",
    procesador: "Dual Core 1.6 GHz",
    memoria_nvram: "2 GB",
    backup: "si",
    sistema_operativo: "Cisco IOS XE",
    version_firmware: "16.12.4",
    dependencia: "Switch Core SW-CORE-01 y SW-CORE-02",
    impacto_caida: "Pérdida de conectividad para 80 usuarios en piso 2, caída de telefonía IP",
    nivel: "alto",
    congenitas: "Puerto GigabitEthernet1/0/5 presenta intermitencia cada 2 meses",
    usuarios_admin: "admin, netadmin",
    correo_admin: "redes@grupocos.com",
    cargo_admin: "Administrador de Redes",
    proveedor_contacto: "Juan Pérez",
    cargo_contacto: "Ingeniero de Soporte",
    telefono_contacto1: "310-555-0101",
    telefono_contacto2: "601-555-0202",
    email_proveedor: "soporte@ciscocolombia.com",
    contacto: "Juan Pérez - Ing. Soporte",
    responsable_proveedor: "Cisco Colombia S.A.",
    fecha_entrega: "2024-06-01",
    tiempo_garantia: "3 años",
    fecha_terminacion: "2027-06-01",
    mantenimientos: [
      {
        fecha: "2024-08-15",
        tipo: "Preventivo",
        descripcion: "Limpieza de puertos y verificación de ventiladores",
        responsable: "Carlos Ramírez"
      },
      {
        fecha: "2024-09-20",
        tipo: "Correctivo",
        descripcion: "Reemplazo de puerto GigabitEthernet1/0/5 por intermitencia",
        responsable: "María González"
      }
    ],
    createdAt: "2024-10-15T10:30:00Z"
  },
  {
    id: "2",
    id_hoja: "HV-FW-002",
    hostname: "HV-FW-EDGE-01",
    activo: "firewall",
    fecha_registro: "2024-09-10",
    ultima_actualizacion: "2024-10-30",
    usuario_creador: "Admin Seguridad",
    version: "1.0",
    razon_social: "grupo cos",
    site: "barranquilla",
    gabinete: "Rack 1 - U8",
    elemento: "firewall",
    marca: "Fortinet",
    modelo: "FortiGate 600E",
    serial: "FG600E1234567890",
    proveedor: "Fortinet Colombia",
    fecha_compra: "2024-08-01",
    ubicacion_fisica: "Sede Barranquilla - Datacenter Edge",
    configuracion: "Firewall perimetral con políticas de seguridad, IPS, Application Control y Web Filtering",
    ip_direccion: "200.123.45.1",
    gateway: "200.123.45.254",
    wins_dns: "8.8.8.8, 1.1.1.1",
    funciones: "Firewall de borde para protección perimetral, VPN site-to-site, NAT, filtrado de contenido",
    procesador: "Fortinet NP6",
    memoria_nvram: "32 GB",
    backup: "si",
    sistema_operativo: "FortiOS",
    version_firmware: "7.4.2",
    dependencia: "ISP Claro Empresarial - Enlace 500Mbps",
    impacto_caida: "Pérdida total de conectividad a Internet para sede Barranquilla (250 usuarios)",
    nivel: "critico",
    congenitas: "Requiere reinicio mensual para optimizar memoria",
    usuarios_admin: "fortiadmin, secadmin",
    correo_admin: "seguridad@grupocos.com",
    cargo_admin: "Administrador de Seguridad",
    proveedor_contacto: "Laura Martínez",
    cargo_contacto: "Ingeniera de Ciberseguridad",
    telefono_contacto1: "320-555-0303",
    telefono_contacto2: "605-555-0404",
    email_proveedor: "soporte@fortinet.com.co",
    contacto: "Laura Martínez - Ing. Ciberseguridad",
    responsable_proveedor: "Fortinet Colombia",
    fecha_entrega: "2024-08-15",
    tiempo_garantia: "5 años",
    fecha_terminacion: "2029-08-15",
    mantenimientos: [
      {
        fecha: "2024-10-01",
        tipo: "Preventivo",
        descripcion: "Actualización de firmas IPS y revisión de políticas",
        responsable: "Pedro Sánchez"
      },
      {
        fecha: "2024-10-15",
        tipo: "Actualización",
        descripcion: "Upgrade de firmware de 7.4.1 a 7.4.2",
        responsable: "Pedro Sánchez"
      }
    ],
    createdAt: "2024-09-10T14:20:00Z"
  },
  {
    id: "3",
    id_hoja: "HV-SW-003",
    hostname: "HV-SW-CARACOL-01",
    activo: "switch",
    fecha_registro: "2024-10-01",
    ultima_actualizacion: "2024-10-30",
    usuario_creador: "Admin Red",
    version: "1.0",
    razon_social: "grupo cos",
    site: "caracol",
    gabinete: "Rack 2 - U15",
    elemento: "switch",
    marca: "Huawei",
    modelo: "S5720-28P-SI",
    serial: "2102351ABC789DEF",
    proveedor: "Huawei Technologies",
    fecha_compra: "2024-07-15",
    ubicacion_fisica: "Edificio Caracol - Sala de Equipos Piso 3",
    configuracion: "Switch de distribución con VLANs para diferentes departamentos",
    ip_direccion: "10.50.10.5",
    gateway: "10.50.10.1",
    wins_dns: "10.50.1.10, 10.50.1.11",
    funciones: "Switch de distribución para edificio Caracol, gestión de VLANs por departamento",
    procesador: "Single Core 800 MHz",
    memoria_nvram: "256 MB",
    backup: "si",
    sistema_operativo: "Huawei VRP",
    version_firmware: "V200R019C10SPC500",
    dependencia: "Router principal R-CARACOL-EDGE",
    impacto_caida: "Pérdida de conectividad para 120 usuarios de diferentes departamentos",
    nivel: "alto",
    congenitas: "Ninguna reportada",
    usuarios_admin: "admin, netop",
    correo_admin: "ti.caracol@grupocos.com",
    cargo_admin: "Coordinador TI Caracol",
    proveedor_contacto: "Roberto Díaz",
    cargo_contacto: "Especialista en Redes",
    telefono_contacto1: "315-555-0505",
    telefono_contacto2: "601-555-0606",
    email_proveedor: "support@huawei.com.co",
    contacto: "Roberto Díaz - Especialista Redes",
    responsable_proveedor: "Huawei Technologies Colombia",
    fecha_entrega: "2024-07-30",
    tiempo_garantia: "2 años",
    fecha_terminacion: "2026-07-30",
    mantenimientos: [
      {
        fecha: "2024-10-10",
        tipo: "Preventivo",
        descripcion: "Limpieza general y revisión de temperatura",
        responsable: "Luis Fernández"
      }
    ],
    createdAt: "2024-10-01T09:15:00Z"
  },
  {
    id: "4",
    id_hoja: "HV-SW-004",
    hostname: "HV-SW-RRHH-ACCESS",
    activo: "switch",
    fecha_registro: "2024-10-20",
    ultima_actualizacion: "2024-10-30",
    usuario_creador: "Admin Red",
    version: "1.0",
    razon_social: "grupo cos",
    site: "RRHH",
    gabinete: "Rack RRHH-A - U10",
    elemento: "switch",
    marca: "Cisco",
    modelo: "Catalyst 2960X-24PS",
    serial: "FOC2201X5TY",
    proveedor: "Cisco Colombia",
    fecha_compra: "2024-09-05",
    ubicacion_fisica: "Departamento RRHH - Sala de Servidores",
    configuracion: "Switch de acceso con PoE para área de Recursos Humanos",
    ip_direccion: "172.16.50.20",
    gateway: "172.16.50.1",
    wins_dns: "172.16.1.10, 8.8.8.8",
    funciones: "Switch de acceso exclusivo para RRHH, gestión de VLAN segmentada con ACL",
    procesador: "Single Core 1.0 GHz",
    memoria_nvram: "128 MB",
    backup: "si",
    sistema_operativo: "Cisco IOS",
    version_firmware: "15.2(7)E2",
    dependencia: "Switch Core SW-CORE-01",
    impacto_caida: "Pérdida de conectividad para 25 usuarios del área de RRHH",
    nivel: "medio",
    congenitas: "Ninguna reportada",
    usuarios_admin: "admin, rrhhadmin",
    correo_admin: "ti.rrhh@grupocos.com",
    cargo_admin: "Administrador TI RRHH",
    proveedor_contacto: "Ana Torres",
    cargo_contacto: "Ingeniera de Soporte",
    telefono_contacto1: "318-555-0707",
    telefono_contacto2: "601-555-0808",
    email_proveedor: "soporte@ciscocolombia.com",
    contacto: "Ana Torres - Ing. Soporte",
    responsable_proveedor: "Cisco Colombia S.A.",
    fecha_entrega: "2024-09-15",
    tiempo_garantia: "3 años",
    fecha_terminacion: "2027-09-15",
    mantenimientos: [],
    createdAt: "2024-10-20T11:45:00Z"
  },
  {
    id: "5",
    id_hoja: "HV-FW-005",
    hostname: "HV-FW-OTD-EDGE",
    activo: "firewall",
    fecha_registro: "2024-10-25",
    ultima_actualizacion: "2024-10-30",
    usuario_creador: "Admin Seguridad",
    version: "1.0",
    razon_social: "otd",
    site: "calle 80",
    gabinete: "Rack OTD-1 - U5",
    elemento: "firewall",
    marca: "Palo Alto Networks",
    modelo: "PA-3220",
    serial: "001801012345",
    proveedor: "Palo Alto Networks",
    fecha_compra: "2024-09-20",
    ubicacion_fisica: "Sede Calle 80 - Datacenter Principal",
    configuracion: "Firewall NGFW con threat prevention, URL filtering y GlobalProtect VPN",
    ip_direccion: "200.200.50.1",
    gateway: "200.200.50.254",
    wins_dns: "1.1.1.1, 8.8.8.8",
    funciones: "Next-Generation Firewall para sede OTD, protección avanzada de amenazas y VPN SSL",
    procesador: "Multi-core Intel",
    memoria_nvram: "16 GB",
    backup: "si",
    sistema_operativo: "PAN-OS",
    version_firmware: "11.1.2",
    dependencia: "ISP ETB Empresarial - Enlace 1Gbps",
    impacto_caida: "Pérdida total de conectividad para sede OTD (180 usuarios) y acceso remoto VPN",
    nivel: "critico",
    congenitas: "Ninguna reportada",
    usuarios_admin: "paadmin, secadmin",
    correo_admin: "seguridad@otd.com.co",
    cargo_admin: "Administrador de Seguridad OTD",
    proveedor_contacto: "Miguel Ángel Rojas",
    cargo_contacto: "Security Architect",
    telefono_contacto1: "322-555-0909",
    telefono_contacto2: "601-555-1010",
    email_proveedor: "support@paloaltonetworks.com",
    contacto: "Miguel Ángel Rojas - Security Architect",
    responsable_proveedor: "Palo Alto Networks",
    fecha_entrega: "2024-10-05",
    tiempo_garantia: "5 años",
    fecha_terminacion: "2029-10-05",
    mantenimientos: [
      {
        fecha: "2024-10-28",
        tipo: "Actualización",
        descripcion: "Actualización de firmas de amenazas y contenido",
        responsable: "Diana Castro"
      }
    ],
    createdAt: "2024-10-25T16:30:00Z"
  }
];

// Función para inicializar datos de ejemplo en localStorage
export function initializeMockData() {
  const existingData = localStorage.getItem('equipmentData');
  
  // Solo inicializar si no hay datos previos
  if (!existingData || JSON.parse(existingData).length === 0) {
    localStorage.setItem('equipmentData', JSON.stringify(mockEquipmentData));
    return true; // Indica que se inicializaron los datos
  }
  
  return false; // Indica que ya había datos
}
